### ISSUE TITLE
大佬太强了，后续是否考虑支持GLM4?谢谢

### ISSUE THREAD

**Issue by visonpon** [DakeQQ/Native-LLM-for-Android#13]

**Comment by DakeQQ** [comment]
您好，感谢您的回复和支持。目前，GLM-4 仅发布了 9B 版本，这是一个在 float32 格式下为 20GB 或在 int8 格式下为 5GB 的模型。使用 ONNX Runtime 时，在加载模型的过程中，模型所需的内存大约是模型文件大小的两倍。这意味着对于 int8 版本，至少需要 10GB 的内存，即使使用 int4 量化，也需要 5GB 的内存。值得注意的是，在最新的 ONNX Runtime 版本 1.20.0 中，int4 推理仍然相对较慢，大约是 int8 速度的三分之一。此外，导出模型的过程大约需要 64GB 的内存，即使使用了 low_cpu_mem_usage=True 设置，这也是一项非常高的硬件要求。目前，我们没有设备来测试 9B 模型。不过，如果您有兴趣，我们可以提供类似的导出脚本，尽管我们尚未对其进行测试。

您真的想使用 ONNX Runtime 在移动设备上运行 9B 模型吗!？我们实际上建议使用 [mlc-llm](https://github.com/mlc-ai/mlc-llm) 或 [mnn-llm](https://github.com/wangzhaode/mnn-llm)仓库来在移动设备上运行大型模型。对于桌面使用，我们建议考虑使用 [vLLM](https://github.com/vllm-project/vllm) 或 [SGLang](https://github.com/sgl-project/sglang) 框架。

**Comment by visonpon** [comment]
好的，谢谢大佬细致的指导和建议，期待大佬后续工作～
