### ISSUE TITLE
关于将modeling_qwen2_vl.py复制到transformers库函数下之后的报错问题

### ISSUE THREAD

**Issue by Wisimla** [DakeQQ/Native-LLM-for-Android#14]
你好，我在使用Qwen2-VL-2B模型运行QwenVL_Export_ABCD.py导出onnx模型的时候，在shutil.copyfile(modified_path_A, transformers_qwen2_path)将文件copy过去之后，提示KeyError: 'mrope'报错。我看了一下是因为在pre-trained model中的config.json文件中有"type": "mrope"字段，而在您提供的modeling_qwen2_vl.py中没有相应进行该字段的处理。请问这个应该如何解决呢？不知道您之前是否遇到过同样的问题。

**Comment by DakeQQ** [comment]
对于错误表示歉意。但是，我们没有遇到任何“mrope”错误。我们正在使用以下环境：Python 3.11、Torch 2.4.1、ONNX 1.17.0、ONNX Runtime 1.20.0 和 Transformers 4.46.3。操作系统：MAC 15.1.1 + M3。Linux 22.04 + Intel。您能否提供更详细的错误信息，以帮助我们快速确定您遇到的问题 : )

**Comment by Wisimla** [comment]
感谢您的回复~经过验证，我之前使用的是Transformers 4.45.0版本的安装包，安装最新版本Transformers之后已经跑通~感谢！

**Comment by Wisimla** [comment]
感谢您的回复经过验证，我之前使用的是Transformers 4.45.0版本的安装包，安装最新版本Transformers之后已经跑通感谢！
