### ISSUE TITLE
关于中文query无法正确运行的问题

### ISSUE THREAD

**Issue by Wisimla** [DakeQQ/Native-LLM-for-Android#15]
您好，我在将模型导出后，将query改成了"请描述图片中的内容。" 的中文描述，但是在运行的时候，在while循环中只进行了一次推理，输出为“图片”这两个字，在第二次ort_session_E.run的时候token_id就已经达到了151645，请问这个是什么原因呢？

**Comment by Wisimla** [comment]
将query改为“描述图片中的内容。”后能够正确运行，query为“请描述图片中的内容。”仍然会出现上述问题。

**Comment by DakeQQ** [comment]
您好，感谢您的反馈。经过复测，我们确认了您所报告的问题。即便我们已经尽力通过原始代码及float32精度进行了详尽的排查，问题依旧未得到解决。为此，我们推测可能存在以下两种原因：

1. ONNX算子在转换过程中可能引发了精度损失。
2. 原始模型在处理特定query时可能存在缺陷。

目前，我们尚未找到有效的解决办法，对此给您带来的不便深感歉意。

**Comment by Wisimla** [comment]
感谢您的回复。我复核了Qwen2-VL原始代码，发现其是使用AutoProcessor.from_pretrained而非AutoTokenizer.from_pretrained进行Tokenizer搭建的，不知道是否是因为这两个编码的方式不同呢？

**Comment by DakeQQ** [comment]
谢谢您的审校。我们刚刚进行了测试，将tokenizer更改为:
```
tokenizer = AutoProcessor.from_pretrained(path).tokenizer
```  
但仍然只回答“图片”。

**Comment by DakeQQ** [comment]
然而，我们使用动态量化模型（q8f32），并使用"请描述图片中的内容。", 可以获得正确的输出。
