### ISSUE TITLE
大佬方便分享下MiniCPM的模型文件吗

### ISSUE THREAD

**Issue by harukakkkkka** [DakeQQ/Native-LLM-for-Android#18]
在云盘路径里只看到了一个通义的。。

**Comment by DakeQQ** [comment]
当然可以，请稍等。

**Comment by DakeQQ** [comment]
Hello,

The [MiniCPM-1B-sft](https://drive.google.com/file/d/12qun73s02MiHQJOGCb7UKPp_VKm3Q1Og/view?usp=drive_link) model is now available, please git the latest MiniCPM_ONNX-1B Android project to use it. This model has been quantized to the uint8 format to better suit common mobile devices, though this process has resulted in some loss of accuracy despite our best efforts during quantization on the ONNX Runtime framework.
