### ISSUE TITLE
您好，遇到一个奇怪问题，在android studio 上同步和编译都没问题，但在手机上进行问答时，回答为空，尝试好几次都这样

### ISSUE THREAD

**Issue by visonpon** [DakeQQ/Native-LLM-for-Android#19]
![1112033253](https://github.com/user-attachments/assets/d217d1f3-e1c8-4a22-b40e-39aa0028445b)

logcat里有这个提示: This is non sticky GC, maxfree is 8388608 minfree is 2097152。 请问如何解决。

**Comment by DakeQQ** [comment]
Hello~
1. 请问您使用的是哪个LLM？  
2. 您采用的是哪种量化方法？  
3. 您使用的手机设备是什么型号？

我们需要再次尝试触发这个问题以便进行深入调查。

**Comment by visonpon** [comment]
1. Qwen_onnx
2. 默认量化，没做修改
3. 手机是红米Note13,内存8G，CPU型号时天玑6080
4. 用的cmake是3.22.1，ndkVersion '27.0.12077973'

前段时间编译该项目在手机上是正常运行的，今天梳理项目重新编译碰到这一问题。然后更新项目（即cmake3.31.0,ndkVersion '28.0.12433566 rc1'版本）也尝试编译了，但回答问题会闪退。

**Comment by DakeQQ** [comment]
我们也不清楚这个 bug 的原因。它可能是由 `libonnxruntime.so` 引起的。请尝试将 NDK 版本降级到 26.3, Android SDK 31, CMake 3.30.5（这是构建时使用的版本）, 在 CMakeLists.txt 中禁用所有flag options, 并重新测试。如果问题仍然存在，目前我们没有修复方法。同时请确保 **arm64-v8a** 目录中的库文件和头文件版本保持匹配不能混用。GitHub 仓库中最新的 **.so** 版本是基于 **ONNXRuntime==1.20.1** 构建的。

**Comment by visonpon** [comment]
问题得到解决了，因为我在编译不同版本时担心apk会直接覆盖，所以修改了build.gradle里的applicationid,将它改回原始值就正常了。目前不清楚这是为什么，因为之前编译其他软件也这么改过，没遇到这个问题。
