### ISSUE TITLE
关于多模态支持

### ISSUE THREAD

**Issue by Achazwl** [DakeQQ/Native-LLM-for-Android#2]
> 在导出MiniCPM-V的过程中, Resampler总报错“aten::_upsample_bilinear2d_aa”算子不支持，因此暂时无法使用多模态交互。

在 MiniCPM-V 的 2.0 版本中 [openbmb/MiniCPM-V-2](https://huggingface.co/openbmb/MiniCPM-V-2/tree/main)，修改后的 Resampler 避免了这个算子，不知道这个版本 ONNX 是否支持呢？

**Comment by zhb-code** [comment]
我看你在面壁那边问了，他们有回应了吗？

**Comment by DakeQQ** [comment]
一楼猫头像那位就是响应了呀

**Comment by Achazwl** [comment]
https://github.com/ggerganov/llama.cpp/pull/6919
我在支持 llama.cpp 的时候，实现方式是将子图固定缩放成 448x448，这样相关算子的形状可以固定，因此可以把算子 bilinear 的运算结果直接存到 checkpoint 里 [比如这样](https://github.com/ggerganov/llama.cpp/pull/6919/files#diff-a04f406b3da82542be5cc7c7fd909ca3ec6c309846f4d519ad379a661c81fd25R331)。整体来说 onnx 不支持确实麻烦一点。
