### ISSUE TITLE
请问一下，将下载的模型放入assets，这个模型是哪个模型文件，是model.onnx吗

### ISSUE THREAD

**Issue by MansonHua** [DakeQQ/Native-LLM-for-Android#20]

**Comment by DakeQQ** [comment]
上传的模型 Qwen2-1.5B，格式为 `.ort`，应放置在 Android 项目 `Qwen_ONNX` 的 `app/src/main/assets` 文件夹中。请确保解压并将 `*.so` 库存储到 `libs/arm64-v8a` 中。最后，构建项目，它应该能够顺利运行。

**Comment by MansonHua** [comment]
感谢及时的回复，我在huggingface下载了Llama的模型，目前已经转为llama.onnx，并且使用q8_f32量化了模型，获得了llama_quanted.onnx，请问哪个代码是将onnx转为llama.ort

**Comment by DakeQQ** [comment]
此 [Python 脚本](https://github.com/DakeQQ/Native-LLM-for-Android/blob/main/Do_Quantize/Dynamic_Quant/q8_f32.py)提供了一键量化、优化和转换为 `.ort` 格式的功能。需要注意的是，ONNX Runtime 同样支持直接加载 `.onnx` 文件。  

如果需要在 `.ort` 和 `.onnx` 之间切换，可以修改以下路径中的模型名称：  
**`Native-LLM-for-Android/Llama_ONNX/app/src/main/cpp/project.h`**，第 **28 行**。  

将代码从：  
```cpp
const std::string file_name_A = "Model_Llama_1B_1024.ort";
```  
修改为：  
```cpp
const std::string file_name_A = "llama_quanted.onnx";
```

**Comment by MansonHua** [comment]
成功了！感谢大佬的指点！
