### ISSUE TITLE
支持Harmony4吗？

### ISSUE THREAD

**Issue by byteDevDesign** [DakeQQ/Native-LLM-for-Android#3]
看到介绍里有写Harmony4上的运行表现，harmony4是不是不兼容apk了？您是怎么在harmony4上测试的？

**Comment by DakeQQ** [comment]
您好~
我就正常的在Android Studio里面Build & Run，然后就能在P40上跑了，具体的鸿蒙apk兼容情况我也不是很清楚，不是我擅长的领域.

**Comment by byteDevDesign** [comment]
谢谢。HarmonyOS 4.0确实支持apk的安装调试。HarmonyOS NEXT不行。

HarmonyOS NEXT是华为在HarmonyOS 4.0之后推出的全新系统，它将完全摆脱Android的影子，实现自主创新和自给自足。与HarmonyOS 4.0不同的是，HarmonyOS NEXT不再支持Android的代码和应用，而是基于华为自主研发的Harmony内核，采用全新的运行时和开发框架，打造纯粹的鸿蒙应用生态。

**Comment by byteDevDesign** [comment]
谢谢
