### ISSUE TITLE
project.cpp  ->  no member named "load" in Tokenizer 27行

### ISSUE THREAD

**Issue by zhb-code** [DakeQQ/Native-LLM-for-Android#4]
按照文档下载模型放入assets文件夹，然后解压libs下arm64-v8a的so文件，然后运行报异常，project.cpp  ->  no member named "load" in Tokenizer 27行
![1718691813063](https://github.com/DakeQQ/Native-LLM-for-Android/assets/170308342/bb90bfb8-5c4c-4f0e-a6f5-b02947677334)
请问这该怎么处理？

**Comment by DakeQQ** [comment]
不好意思呢. 已经修复, 您再重新抓一份tokenizer.hpp，tokenizer.cpp.

**Comment by zhb-code** [comment]
OK了，run起来了，反应速度确实如你所说，非常快！赞！
