### ISSUE TITLE
模型加载慢

### ISSUE THREAD

**Issue by XXGUI** [DakeQQ/Native-LLM-for-Android#7]
模型加载比较慢，在后续版本中会有什么方案优化加载速度吗。
当前版本加载不稳定会出现加载卡死占用整个设备资源导致操作不了设备
加载速度也是时快时慢

**Comment by DakeQQ** [comment]
您好，感谢您的支持和建议。关于加载缓慢和卡顿的问题，这是由于ONNX Runtime框架在处理模型时的内存使用方式所致。ORT在从ROM加载模型到RAM并创建Session时，会调用复制方法，这导致内存峰值消耗是模型尺寸的两倍（可通过Android Studio Profiler监测）。以下是一些可行的解决方案：

1. 将模型切分为多块，并通过创建多个Session来读取各块模型。但**ORT-Android框架不能使用动态输入（从没跑成功过），因此需要先开固定数组，再通过Slice操作来完成模型的拼接**。这方法的缺点是会增加小模型之间的衔接复杂度並拖慢推理速度。

2. 将模型的权重单独保存，并通过参数传递的方式输入计算主干网络。这会导致无法使用ONNX框架自带的动态量化整形计算(i8mm-MatmulInteger)，只能使用很慢的MatmulFloat，推理速度大概是1/3。

3. 使用混合精度量化方法（如q4_q8_f16.py），可将模型尺寸比INT8再缩小约40%。但ORT-v1.19.2对INT4的推理速度也慢，约为INT8的1/3。

目前没有完美的方法能同时兼顾推理速度和加载效率。如果可以接受推理速度的降低，我建议使用第一种方案。如需进一步讨论或安排更新，请随时联系。

（“时快时慢”应该是手机操作系统检测到大内存占用的调度问题）
