### ISSUE TITLE
any plans for llama3.2?

### ISSUE THREAD

**Issue by radenmuazhuda** [DakeQQ/Native-LLM-for-Android#9]

**Comment by DakeQQ** [comment]
Sure, we’ll review the Llama 3.2 1B version. If we successfully deploy it, we’ll notify you promptly. The target date is set for 2024/11/18.

**Comment by DakeQQ** [comment]
Hello, the Llama 3.2-1B-Instruct model is now available.

**Comment by scsonic** [comment]
modify path in Llama_Export.py 
onnx_model_A = '/home/dake/Downloads/Llama_ONNX/llama.onnx'

**Comment by DakeQQ** [comment]
The file `onnx_model_A = '/home/dake/Downloads/Llama_ONNX/llama.onnx'` is the freshly exported float32 model, while `Model_Llama_1B_1024.ort` is the quantized and optimized version. You can use the optimization script [Do_Quantize/Dynamic_Quant](https://github.com/DakeQQ/Native-LLM-for-Android/tree/main/Do_Quantize/Dynamic_Quant) at your discretion.

Note: Dynamic quantization to int8 format causes noticeable accuracy loss for Llama3.2-1B-Instruct.

**Comment by scsonic** [comment]
its working:
1. install ubuntu, instead of mac
2. modify export and do quantize
3. force set the is large model = true, do not check model size
4. rename the output ort to asset folder

trying Llama-3.2-3B-Instruct now

**Comment by DakeQQ** [comment]
5. Modify the project.h line 33: `const int past_key_value_size = 28 * 8 * 128 * max_token_history;`
